baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Deoksoon Kim
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Biography
          url: bio/
          weight: 10
        - name: Publications
          url: pubs/
          weight: 20
        - name: Experience
          url: exp/
          weight: 30
        - name: Research
          url: res/
          weight: 40
        - name: Courses
          url: courses/
          weight: 50
        - name: TEL
          url: https://www.bc.edu/bc-web/schools/lynch-school/sites/labs/transformative-education-lab.html
          weight: 60

params:
    description: "Research publications, academic experience, and professional biography of Deoksoon Kim, Ph.D., Professor at Boston College."
    author: Deoksoon Kim, Ph.D.
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: false
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowAllPagesInArchive: false
    MainSections: ["biography", "publications", "experience"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Deoksoon Kim, Ph.D.
          subtitle: "Professor at the Lynch School of Education and Human Development, Boston College. My research focuses on understanding the needs of immigrant students to facilitate English acquisition and academic success through instructional technology."
          imageUrl: "avatar.jpg"
          imageWidth: 120
          imageHeight: 120
          buttons:
            - name: Biography
              url: bio/
            - name: Publications
              url: pubs/
            - name: Experience
              url: exp/
            - name: Research
              url: res/
            - name: Courses
              url: courses/
            - name: Transformative Education Lab (TEL)
              url: https://www.bc.edu/bc-web/schools/lynch-school/sites/labs/transformative-education-lab.html

    socialIcons:
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=en&user=YvCec_sAAAAJ
        - name: YouTube
          url: https://www.youtube.com/@TLABTogether
        - name: Email
          url: https://www.bc.edu/content/bc-web/schools/lynch-school/sites/labs/transformative-education-lab/media-library/newsletter-archive.html
        # - name: Bluesky
        #   url: https://bsky.app/profile/pmichaillat.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Deoksoon Kim"
      icon: "favicon-16x16.png"
      iconHeight: 36

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2